### ISSUE TITLE
error

### ISSUE THREAD

**Issue by apepenkov** [TelegramBot/Api#159]
root@vps7987:~# php /var/www/apepenkov.cf/index.php

PHP Notice:  Undefined variable: name in /var/www/apepenkov.cf/index.php on line 67
PHP Fatal error:  Uncaught TelegramBot\Api\InvalidJsonException: Syntax error in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php:284
Stack trace:
#0 /var/www/apepenkov.cf/vendor/telegram-bot/api/src/Client.php(134): TelegramBot\Api\BotApi::jsonValidate('', true)
#1 /var/www/apepenkov.cf/index.php(72): TelegramBot\Api\Client->run()
#2 {main}
  thrown in /var/www/apepenkov.cf/vendor/telegram-bot/api/src/BotApi.php on line 284

**Comment by apepenkov** [comment]
index.php:
`<?php header('Content-Type: text/html; charset=utf-8');
/* Исходники с сайта
* https://djdiplomat.ru/kak-napist-telegram-bot-na-php
* v1.0.0
*/
// подключаемся к API
require_once("vendor/autoload.php");
// создаем переменную бота
$token = "606393979:AAHvVgrMbbLZFW6ImL9m953Q5LBGu5an5ao";
$bot = new \TelegramBot\Api\Client($token);

// если бот еще не зарегистрирован - регистрируем
/** if (!file_exists("registered.trigger")) {

 $page_url = "https://".$_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
 $result = $bot->setWebhook($page_url);
 if($result){
	file_put_contents("registered.trigger",time()); // создаем файл дабы остановить повторные регистрации
 }
} **/

// обязательное. Запуск бота
$bot->command('start', function ($message) use ($bot) {
 $answer = 'Добро пожаловать!';
 $bot->sendMessage($message->getChat()->getId(), $answer);
});
// помощь
$bot->command('help', function ($message) use ($bot) {
 $answer = 'Команды:
 /help - помощь';
 $bot->sendMessage($message->getChat()->getId(), $answer);
});

// передаем картинку
$bot->command('getpic', function ($message) use ($bot) {
 $pic = "https://djdiplomat.ru/wp-content/uploads/forbot.jpg";
 $bot->sendPhoto($message->getChat()->getId(), $pic);
});

// передаем документ
$bot->command('getdoc', function ($message) use ($bot) {
 $document = new \CURLFile('sendfrombot.txt');
 $bot->sendDocument($message->getChat()->getId(), $document);
});

// передаем войс
$bot->command('getvoice', function ($message) use ($bot) {
 $voice = "https://djdiplomat.ru/wp-content/uploads/glazunov_maxim-prividenie.mp3";
 $bot->sendVoice(
 $message->getChat()->getId(),
 $voice //,
 //$duration,
 //$replyToMessageId,
 //$replyMarkup,
 //$disableNotification
 );
});

// болталка
$bot->on(function($Update) use ($bot){
 $message = $Update->getMessage();
 $mtext = $message->getText();
 $cid = $message->getChat()->getId();
 if(mb_stripos($mtext,"привет бот") !== false){
	$bot->sendMessage($message->getChat()->getId(), "и тебе здорова, чувак!");
 }
}, function($message) use ($name){
 return true; // когда тут true - команда проходит
});

// запускаем обработку
$bot->run();
?>`

**Comment by BoShurik** [comment]
What library version do you use?
```bash
composer info telegram-bot/api
```
and php version
```bash
php -v
```

**Comment by apepenkov** [comment]
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies


i installed composer  locally.
 "telegram-bot/api": "^2.3"

**Comment by apepenkov** [comment]
я ставил его с помощью json

**Comment by BoShurik** [comment]
https://github.com/TelegramBot/Api/issues/127
