### ISSUE TITLE
Error: Uncaught exception 'TelegramBot\Api\HttpException' with message 'Not Found' in /home/h17699c/public_html/module/vendor/telegram-bot/api/src/BotApi.php:281

### ISSUE THREAD

**Issue by igorwebb** [TelegramBot/Api#162]
```
header('Content-Type: text/html; charset=utf-8');

require_once("module/vendor/autoload.php");

if(true){
    error_reporting(E_ALL & ~(E_NOTICE | E_USER_NOTICE | E_DEPRECATED));
    ini_set('display_errors', 1);
}

$bot = new \TelegramBot\Api\Client($INI['key']);

$bot->command('start', function ($message) use ($bot) {
    $answer = 'Добро пожаловать!';
    $bot->sendMessage($message->getChat()->getId(), $answer);
});

$bot->run();

echo "I am working. Do not bother me, please.";
```

Error in log (I send message "/start" to my bot): 

```
PHP Fatal error:  Uncaught exception 'TelegramBot\Api\HttpException' with message 'Not Found' in /home/h17699c/public_html/module/vendor/telegram-bot/api/src/BotApi.php:281
Stack trace:
#0 /home/h17699c/public_html/module/vendor/telegram-bot/api/src/BotApi.php(258): TelegramBot\Api\BotApi::curlValidate(Resource id #14, '{"ok":false,"er...')
#1 /home/h17699c/public_html/module/vendor/telegram-bot/api/src/BotApi.php(227): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /home/h17699c/public_html/module/vendor/telegram-bot/api/src/BotApi.php(338): TelegramBot\Api\BotApi->call('sendMessage', Array)
#3 [internal function]: TelegramBot\Api\BotApi->sendMessage(195796903, '\xD0\x94\xD0\xBE\xD0\xB1\xD1\x80\xD0\xBE \xD0\xBF\xD0\xBE...')
#4 /home/h17699c/public_html/module/vendor/telegram-bot/api/src/Client.php(405): call_user_func_array(Array, Array)
#5 /home/h17699c/public_html/bot.php(18): TelegramBot\Api\Client->__call('sendMessage', Array)
#6 /home/h17699c/public_html/bot.php(18): TelegramBot\Api\Client->sendMessage(195796903, '\xD0\x9 in /home/h17699c/public_html/module/vendor/telegram-bot/api/src/BotApi.php on line 281
```

Webhook is set. Before the change of hosting with old api version everything worked. Now i download with composer - v2.3.13

Bot URL - https://www.ru/?p=bot

UPD:

If i use this code:
```
header('Content-Type: text/html; charset=utf-8');

require_once("module/vendor/autoload.php");

if(true){
    error_reporting(E_ALL & ~(E_NOTICE | E_USER_NOTICE | E_DEPRECATED));
    ini_set('display_errors', 1);
}

try {

$bot = new \TelegramBot\Api\Client($INI['key']);

$bot->command('start', function ($message) use ($bot) {
    $answer = 'Добро пожаловать!';
    $bot->sendMessage($message->getChat()->getId(), $answer);
});

$bot->run();

} catch (\TelegramBot\Api\Exception $e) {
    $e->getMessage();
}

echo "I am working. Do not bother me, please.";
```

- log is empty, but bot do not send me answer.

In https://api.telegram.org/botTOKEN/getWebhookinfo are no errors in it

**Comment by igorwebb** [comment]
Trouble in Free SSL (letencrypt)...
