### ISSUE TITLE
getUpdates method: Fatal error:  Uncaught exception 'TelegramBot\Api\HttpException' with message 'Conflict'

### ISSUE THREAD

**Issue by 666b666** [TelegramBot/Api#68]
hi there
i'm completely noob at this repository
phpcode:
<?

$updates  = $bot->getUpdates();
print_r($updates);

when i trying to  use getUpdates method, i get this err:

```
<pre>
Fatal error:  Uncaught exception 'TelegramBot\Api\HttpException' with message 'Conflict' in /path/to/vendor/vendor/telegram-bot/api/src/BotApi.php:261
Stack trace:
#0 /path/to/vendor/telegram-bot/api/src/BotApi.php(241): 
TelegramBot\Api\BotApi::curlValidate(Resource id #7)
#1/path/to/vendor/telegram-bot/api/src/BotApi.php(210): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /path/to/vendor/telegram-bot/api/src/BotApi.php(453): TelegramBot\Api\BotApi->call('getUpdates', Array)
#3 /path/to/bot/bot.php(10): TelegramBot\Api\BotApi->getUpdates()
#4 {main}
  thrown in /path/to/vendor/telegram-bot/api/src/BotApi.php on line 261
</pre>
```

what's wrong?
is there any **COMPLETE** guide to use all methods?

**Comment by YaroslavMolchan** [comment]
@666b666 it's error from Telegram Bot API, I can extend error text is it possible in next update.
